// Generated by scripts/generate-renderer-activation-contract.mjs. Do not edit.

use std::fmt;

pub const RENDERER_ACTIVATION_SCHEMA_VERSION: u16 = 1;
pub const RENDERER_ACTIVATION_QUERY_EXPORT: &str = "MacTypeQueryActivationEvidenceV1";
pub const RENDERER_ACTIVATION_EVIDENCE_V1_SIZE: usize = 312;
pub const RUNTIME_GENERATION_CANONICAL_CHARS: usize = 64;
pub const RUNTIME_GENERATION_TEXT_BYTES: usize = 65;
pub const PROFILE_DIGEST_CANONICAL_CHARS: usize = 71;
pub const PROFILE_DIGEST_TEXT_BYTES: usize = 72;
pub const PROFILE_DIGEST_PREFIX: &str = "sha256:";

#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RendererArchitecture {
    X86 = 1,
    X64 = 2,
}

impl RendererArchitecture {
    pub const fn code(self) -> &'static str {
        match self {
            Self::X86 => "x86",
            Self::X64 => "x64",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "x86" => Some(Self::X86),
            "x64" => Some(Self::X64),
            _ => None,
        }
    }
}

impl TryFrom<u8> for RendererArchitecture {
    type Error = RendererActivationContractError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::X86),
            2 => Ok(Self::X64),
            _ => Err(RendererActivationContractError::InvalidArchitecture),
        }
    }
}

#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RendererModuleLoad {
    NotLoaded = 1,
    LoadedByRequest = 2,
    AlreadyLoaded = 3,
    Unknown = 4,
}

impl RendererModuleLoad {
    pub const fn code(self) -> &'static str {
        match self {
            Self::NotLoaded => "not-loaded",
            Self::LoadedByRequest => "loaded-by-request",
            Self::AlreadyLoaded => "already-loaded",
            Self::Unknown => "unknown",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "not-loaded" => Some(Self::NotLoaded),
            "loaded-by-request" => Some(Self::LoadedByRequest),
            "already-loaded" => Some(Self::AlreadyLoaded),
            "unknown" => Some(Self::Unknown),
            _ => None,
        }
    }
}

impl TryFrom<u8> for RendererModuleLoad {
    type Error = RendererActivationContractError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::NotLoaded),
            2 => Ok(Self::LoadedByRequest),
            3 => Ok(Self::AlreadyLoaded),
            4 => Ok(Self::Unknown),
            _ => Err(RendererActivationContractError::InvalidModuleLoad),
        }
    }
}

#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RendererActivationDisposition {
    Active = 1,
    QuietSkip = 2,
    Failed = 3,
}

impl RendererActivationDisposition {
    pub const fn code(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::QuietSkip => "quiet-skip",
            Self::Failed => "failed",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "active" => Some(Self::Active),
            "quiet-skip" => Some(Self::QuietSkip),
            "failed" => Some(Self::Failed),
            _ => None,
        }
    }
}

impl TryFrom<u8> for RendererActivationDisposition {
    type Error = RendererActivationContractError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::Active),
            2 => Ok(Self::QuietSkip),
            3 => Ok(Self::Failed),
            _ => Err(RendererActivationContractError::InvalidActivationDisposition),
        }
    }
}

#[repr(u16)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RendererActivationReason {
    None = 0,
    ProfileMissing = 1,
    ProfileInvalid = 2,
    ProfileDigestMismatch = 3,
    ProcessExcluded = 4,
    ProcessUnloadRequested = 5,
    RuntimeGenerationMismatch = 6,
    InitializationFailed = 7,
    HookTransactionFailed = 8,
    LifecycleStopping = 9,
    EvidenceUnavailable = 10,
    UnsupportedContract = 11,
    ModuleLoadFailed = 12,
    ModuleUnloadFailed = 13,
}

impl RendererActivationReason {
    pub const fn code(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::ProfileMissing => "profile-missing",
            Self::ProfileInvalid => "profile-invalid",
            Self::ProfileDigestMismatch => "profile-digest-mismatch",
            Self::ProcessExcluded => "process-excluded",
            Self::ProcessUnloadRequested => "process-unload-requested",
            Self::RuntimeGenerationMismatch => "runtime-generation-mismatch",
            Self::InitializationFailed => "initialization-failed",
            Self::HookTransactionFailed => "hook-transaction-failed",
            Self::LifecycleStopping => "lifecycle-stopping",
            Self::EvidenceUnavailable => "evidence-unavailable",
            Self::UnsupportedContract => "unsupported-contract",
            Self::ModuleLoadFailed => "module-load-failed",
            Self::ModuleUnloadFailed => "module-unload-failed",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "none" => Some(Self::None),
            "profile-missing" => Some(Self::ProfileMissing),
            "profile-invalid" => Some(Self::ProfileInvalid),
            "profile-digest-mismatch" => Some(Self::ProfileDigestMismatch),
            "process-excluded" => Some(Self::ProcessExcluded),
            "process-unload-requested" => Some(Self::ProcessUnloadRequested),
            "runtime-generation-mismatch" => Some(Self::RuntimeGenerationMismatch),
            "initialization-failed" => Some(Self::InitializationFailed),
            "hook-transaction-failed" => Some(Self::HookTransactionFailed),
            "lifecycle-stopping" => Some(Self::LifecycleStopping),
            "evidence-unavailable" => Some(Self::EvidenceUnavailable),
            "unsupported-contract" => Some(Self::UnsupportedContract),
            "module-load-failed" => Some(Self::ModuleLoadFailed),
            "module-unload-failed" => Some(Self::ModuleUnloadFailed),
            _ => None,
        }
    }
}

impl TryFrom<u16> for RendererActivationReason {
    type Error = RendererActivationContractError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::None),
            1 => Ok(Self::ProfileMissing),
            2 => Ok(Self::ProfileInvalid),
            3 => Ok(Self::ProfileDigestMismatch),
            4 => Ok(Self::ProcessExcluded),
            5 => Ok(Self::ProcessUnloadRequested),
            6 => Ok(Self::RuntimeGenerationMismatch),
            7 => Ok(Self::InitializationFailed),
            8 => Ok(Self::HookTransactionFailed),
            9 => Ok(Self::LifecycleStopping),
            10 => Ok(Self::EvidenceUnavailable),
            11 => Ok(Self::UnsupportedContract),
            12 => Ok(Self::ModuleLoadFailed),
            13 => Ok(Self::ModuleUnloadFailed),
            _ => Err(RendererActivationContractError::InvalidActivationReason),
        }
    }
}

#[repr(u64)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RendererCapability {
    Gdi = 1_u64 << 0,
    ChildInjection = 1_u64 << 1,
    DirectWrite = 1_u64 << 2,
    DirectWriteCore = 1_u64 << 3,
    Direct2d = 1_u64 << 4,
    GdiPlus = 1_u64 << 5,
    FontSubstitution = 1_u64 << 6,
    UnityFont = 1_u64 << 7,
}

impl RendererCapability {
    pub const fn bit(self) -> u64 {
        self as u64
    }

    pub const fn code(self) -> &'static str {
        match self {
            Self::Gdi => "gdi",
            Self::ChildInjection => "child-injection",
            Self::DirectWrite => "direct-write",
            Self::DirectWriteCore => "direct-write-core",
            Self::Direct2d => "direct2d",
            Self::GdiPlus => "gdi-plus",
            Self::FontSubstitution => "font-substitution",
            Self::UnityFont => "unity-font",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "gdi" => Some(Self::Gdi),
            "child-injection" => Some(Self::ChildInjection),
            "direct-write" => Some(Self::DirectWrite),
            "direct-write-core" => Some(Self::DirectWriteCore),
            "direct2d" => Some(Self::Direct2d),
            "gdi-plus" => Some(Self::GdiPlus),
            "font-substitution" => Some(Self::FontSubstitution),
            "unity-font" => Some(Self::UnityFont),
            _ => None,
        }
    }
}

pub const RENDERER_CAPABILITY_KNOWN_MASK: u64 = RendererCapability::Gdi as u64
    | RendererCapability::ChildInjection as u64
    | RendererCapability::DirectWrite as u64
    | RendererCapability::DirectWriteCore as u64
    | RendererCapability::Direct2d as u64
    | RendererCapability::GdiPlus as u64
    | RendererCapability::FontSubstitution as u64
    | RendererCapability::UnityFont as u64;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RendererCapabilitySet(u64);

impl RendererCapabilitySet {
    pub fn from_bits(bits: u64) -> Result<Self, RendererActivationContractError> {
        if bits & !RENDERER_CAPABILITY_KNOWN_MASK != 0 {
            Err(RendererActivationContractError::InvalidCapabilityMask)
        } else {
            Ok(Self(bits))
        }
    }

    pub const fn bits(self) -> u64 {
        self.0
    }

    pub const fn contains(self, capability: RendererCapability) -> bool {
        self.0 & capability.bit() != 0
    }
}

#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct RuntimeGenerationId([u8; RUNTIME_GENERATION_TEXT_BYTES]);

impl RuntimeGenerationId {
    pub fn parse(value: &str) -> Result<Self, RendererActivationContractError> {
        if !canonical_runtime_generation(value.as_bytes()) {
            return Err(RendererActivationContractError::InvalidRuntimeGenerationId);
        }
        let mut wire = [0; RUNTIME_GENERATION_TEXT_BYTES];
        wire[..RUNTIME_GENERATION_CANONICAL_CHARS].copy_from_slice(value.as_bytes());
        Ok(Self(wire))
    }

    pub fn as_str(&self) -> &str {
        std::str::from_utf8(&self.0[..RUNTIME_GENERATION_CANONICAL_CHARS])
            .expect("a validated runtime generation is ASCII")
    }

    pub const fn as_wire_bytes(&self) -> &[u8; RUNTIME_GENERATION_TEXT_BYTES] {
        &self.0
    }
}

impl fmt::Display for RuntimeGenerationId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct ProfileDigest([u8; PROFILE_DIGEST_TEXT_BYTES]);

impl ProfileDigest {
    pub fn parse(value: &str) -> Result<Self, RendererActivationContractError> {
        if !canonical_profile_digest(value.as_bytes()) {
            return Err(RendererActivationContractError::InvalidProfileDigest);
        }
        let mut wire = [0; PROFILE_DIGEST_TEXT_BYTES];
        wire[..PROFILE_DIGEST_CANONICAL_CHARS].copy_from_slice(value.as_bytes());
        Ok(Self(wire))
    }

    pub fn as_str(&self) -> &str {
        std::str::from_utf8(&self.0[..PROFILE_DIGEST_CANONICAL_CHARS])
            .expect("a validated profile digest is ASCII")
    }

    pub const fn as_wire_bytes(&self) -> &[u8; PROFILE_DIGEST_TEXT_BYTES] {
        &self.0
    }
}

impl fmt::Display for ProfileDigest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RendererRuntimeBinding {
    runtime_generation_id: RuntimeGenerationId,
    profile_digest: ProfileDigest,
}

impl RendererRuntimeBinding {
    pub const fn new(
        runtime_generation_id: RuntimeGenerationId,
        profile_digest: ProfileDigest,
    ) -> Self {
        Self {
            runtime_generation_id,
            profile_digest,
        }
    }

    pub const fn runtime_generation_id(&self) -> &RuntimeGenerationId {
        &self.runtime_generation_id
    }

    pub const fn profile_digest(&self) -> &ProfileDigest {
        &self.profile_digest
    }

    fn validate(&self) -> Result<(), RendererActivationContractError> {
        if !canonical_runtime_generation_wire(&self.runtime_generation_id.0) {
            return Err(RendererActivationContractError::InvalidRuntimeGenerationId);
        }
        if !canonical_profile_digest_wire(&self.profile_digest.0) {
            return Err(RendererActivationContractError::InvalidProfileDigest);
        }
        Ok(())
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RendererProcessIdentity {
    pub pid: u32,
    pub creation_time: u64,
    pub session_id: u32,
    pub architecture: RendererArchitecture,
}

#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RendererActivationEvidenceV1 {
    pub struct_size: u32,
    pub schema_version: u16,
    pub reason: u16,
    pub architecture: u8,
    pub module_load: u8,
    pub disposition: u8,
    pub reserved0: u8,
    pub pid: u32,
    pub session_id: u32,
    pub reserved1: u32,
    pub creation_time: u64,
    pub binding: RendererRuntimeBinding,
    pub effective_profile_digest: [u8; PROFILE_DIGEST_TEXT_BYTES],
    pub reserved_alignment: [u8; 7],
    pub lifecycle_revision: u64,
    pub capability_active: u64,
    pub capability_unavailable: u64,
    pub capability_failed: u64,
    pub reserved: [u8; 32],
}

impl RendererActivationEvidenceV1 {
    pub fn request(
        identity: RendererProcessIdentity,
        binding: RendererRuntimeBinding,
        module_load: RendererModuleLoad,
    ) -> Self {
        Self {
            struct_size: RENDERER_ACTIVATION_EVIDENCE_V1_SIZE as u32,
            schema_version: RENDERER_ACTIVATION_SCHEMA_VERSION,
            reason: RendererActivationReason::None as u16,
            architecture: identity.architecture as u8,
            module_load: module_load as u8,
            disposition: 0,
            reserved0: 0,
            pid: identity.pid,
            session_id: identity.session_id,
            reserved1: 0,
            creation_time: identity.creation_time,
            binding,
            effective_profile_digest: [0; PROFILE_DIGEST_TEXT_BYTES],
            reserved_alignment: [0; 7],
            lifecycle_revision: 0,
            capability_active: 0,
            capability_unavailable: 0,
            capability_failed: 0,
            reserved: [0; 32],
        }
    }

    pub fn validate_request(&self) -> Result<(), RendererActivationContractError> {
        self.validate_common()?;
        if self.reason != RendererActivationReason::None as u16
            || !matches!(
                RendererModuleLoad::try_from(self.module_load),
                Ok(RendererModuleLoad::LoadedByRequest) | Ok(RendererModuleLoad::AlreadyLoaded)
            )
            || self.disposition != 0
            || self.lifecycle_revision != 0
            || self.capability_active != 0
            || self.capability_unavailable != 0
            || self.capability_failed != 0
            || !all_zero(&self.effective_profile_digest)
        {
            return Err(RendererActivationContractError::NonzeroRequestOutput);
        }
        Ok(())
    }

    pub fn validate(&self) -> Result<(), RendererActivationContractError> {
        self.validate_common()?;
        let module_load = RendererModuleLoad::try_from(self.module_load)?;
        let disposition = RendererActivationDisposition::try_from(self.disposition)?;
        let reason = RendererActivationReason::try_from(self.reason)?;
        let all_capabilities =
            self.capability_active | self.capability_unavailable | self.capability_failed;
        if all_capabilities & !RENDERER_CAPABILITY_KNOWN_MASK != 0 {
            return Err(RendererActivationContractError::InvalidCapabilityMask);
        }
        if self.capability_active & self.capability_unavailable != 0
            || self.capability_active & self.capability_failed != 0
            || self.capability_unavailable & self.capability_failed != 0
        {
            return Err(RendererActivationContractError::OverlappingCapabilities);
        }
        let effective = self.effective_profile_digest()?;
        let binding_matches = effective.as_ref() == Some(self.binding.profile_digest());
        let consistent = match disposition {
            RendererActivationDisposition::Active => {
                matches!(
                    module_load,
                    RendererModuleLoad::LoadedByRequest | RendererModuleLoad::AlreadyLoaded
                ) && reason == RendererActivationReason::None
                    && self.lifecycle_revision != 0
                    && binding_matches
            }
            RendererActivationDisposition::QuietSkip => {
                matches!(
                    module_load,
                    RendererModuleLoad::LoadedByRequest | RendererModuleLoad::AlreadyLoaded
                ) && reason != RendererActivationReason::None
                    && self.lifecycle_revision != 0
                    && self.capability_active == 0
                    && self.capability_failed == 0
                    && binding_matches
            }
            RendererActivationDisposition::Failed => reason != RendererActivationReason::None,
        };
        if !consistent {
            return Err(RendererActivationContractError::InconsistentEvidence);
        }
        Ok(())
    }

    pub fn identity(&self) -> Result<RendererProcessIdentity, RendererActivationContractError> {
        Ok(RendererProcessIdentity {
            pid: self.pid,
            creation_time: self.creation_time,
            session_id: self.session_id,
            architecture: RendererArchitecture::try_from(self.architecture)?,
        })
    }

    pub fn disposition(
        &self,
    ) -> Result<RendererActivationDisposition, RendererActivationContractError> {
        RendererActivationDisposition::try_from(self.disposition)
    }

    pub fn reason(&self) -> Result<RendererActivationReason, RendererActivationContractError> {
        RendererActivationReason::try_from(self.reason)
    }

    pub fn effective_profile_digest(
        &self,
    ) -> Result<Option<ProfileDigest>, RendererActivationContractError> {
        if all_zero(&self.effective_profile_digest) {
            return Ok(None);
        }
        if !canonical_profile_digest_wire(&self.effective_profile_digest) {
            return Err(RendererActivationContractError::InvalidProfileDigest);
        }
        Ok(Some(ProfileDigest(self.effective_profile_digest)))
    }

    pub fn active_capabilities(
        &self,
    ) -> Result<RendererCapabilitySet, RendererActivationContractError> {
        RendererCapabilitySet::from_bits(self.capability_active)
    }

    pub fn unavailable_capabilities(
        &self,
    ) -> Result<RendererCapabilitySet, RendererActivationContractError> {
        RendererCapabilitySet::from_bits(self.capability_unavailable)
    }

    pub fn failed_capabilities(
        &self,
    ) -> Result<RendererCapabilitySet, RendererActivationContractError> {
        RendererCapabilitySet::from_bits(self.capability_failed)
    }

    pub fn to_wire_bytes(&self) -> [u8; RENDERER_ACTIVATION_EVIDENCE_V1_SIZE] {
        let mut wire = [0; RENDERER_ACTIVATION_EVIDENCE_V1_SIZE];
        put(&mut wire, 0, &self.struct_size.to_le_bytes());
        put(&mut wire, 4, &self.schema_version.to_le_bytes());
        put(&mut wire, 6, &self.reason.to_le_bytes());
        wire[8] = self.architecture;
        wire[9] = self.module_load;
        wire[10] = self.disposition;
        wire[11] = self.reserved0;
        put(&mut wire, 12, &self.pid.to_le_bytes());
        put(&mut wire, 16, &self.session_id.to_le_bytes());
        put(&mut wire, 20, &self.reserved1.to_le_bytes());
        put(&mut wire, 24, &self.creation_time.to_le_bytes());
        put(
            &mut wire,
            32,
            self.binding.runtime_generation_id.as_wire_bytes(),
        );
        put(&mut wire, 97, self.binding.profile_digest.as_wire_bytes());
        put(&mut wire, 169, &self.effective_profile_digest);
        put(&mut wire, 241, &self.reserved_alignment);
        put(&mut wire, 248, &self.lifecycle_revision.to_le_bytes());
        put(&mut wire, 256, &self.capability_active.to_le_bytes());
        put(&mut wire, 264, &self.capability_unavailable.to_le_bytes());
        put(&mut wire, 272, &self.capability_failed.to_le_bytes());
        put(&mut wire, 280, &self.reserved);
        wire
    }

    pub fn request_from_wire_bytes(bytes: &[u8]) -> Result<Self, RendererActivationContractError> {
        let request = Self::decode_wire(bytes)?;
        request.validate_request()?;
        Ok(request)
    }

    pub fn from_wire_bytes(bytes: &[u8]) -> Result<Self, RendererActivationContractError> {
        let evidence = Self::decode_wire(bytes)?;
        evidence.validate()?;
        Ok(evidence)
    }

    fn decode_wire(bytes: &[u8]) -> Result<Self, RendererActivationContractError> {
        if bytes.len() != RENDERER_ACTIVATION_EVIDENCE_V1_SIZE {
            return Err(RendererActivationContractError::InvalidWireSize);
        }
        let mut runtime_generation_id = [0; RUNTIME_GENERATION_TEXT_BYTES];
        runtime_generation_id.copy_from_slice(&bytes[32..97]);
        let mut profile_digest = [0; PROFILE_DIGEST_TEXT_BYTES];
        profile_digest.copy_from_slice(&bytes[97..169]);
        let mut effective_profile_digest = [0; PROFILE_DIGEST_TEXT_BYTES];
        effective_profile_digest.copy_from_slice(&bytes[169..241]);
        let mut reserved_alignment = [0; 7];
        reserved_alignment.copy_from_slice(&bytes[241..248]);
        let mut reserved = [0; 32];
        reserved.copy_from_slice(&bytes[280..312]);
        Ok(Self {
            struct_size: read_u32(bytes, 0),
            schema_version: read_u16(bytes, 4),
            reason: read_u16(bytes, 6),
            architecture: bytes[8],
            module_load: bytes[9],
            disposition: bytes[10],
            reserved0: bytes[11],
            pid: read_u32(bytes, 12),
            session_id: read_u32(bytes, 16),
            reserved1: read_u32(bytes, 20),
            creation_time: read_u64(bytes, 24),
            binding: RendererRuntimeBinding {
                runtime_generation_id: RuntimeGenerationId(runtime_generation_id),
                profile_digest: ProfileDigest(profile_digest),
            },
            effective_profile_digest,
            reserved_alignment,
            lifecycle_revision: read_u64(bytes, 248),
            capability_active: read_u64(bytes, 256),
            capability_unavailable: read_u64(bytes, 264),
            capability_failed: read_u64(bytes, 272),
            reserved,
        })
    }

    fn validate_common(&self) -> Result<(), RendererActivationContractError> {
        if self.struct_size as usize != RENDERER_ACTIVATION_EVIDENCE_V1_SIZE {
            return Err(RendererActivationContractError::InvalidStructSize);
        }
        if self.schema_version != RENDERER_ACTIVATION_SCHEMA_VERSION {
            return Err(RendererActivationContractError::UnsupportedVersion);
        }
        RendererArchitecture::try_from(self.architecture)?;
        if self.pid == 0 || self.creation_time == 0 || self.session_id == 0 {
            return Err(RendererActivationContractError::InvalidIdentity);
        }
        if self.reserved0 != 0
            || self.reserved1 != 0
            || !all_zero(&self.reserved_alignment)
            || !all_zero(&self.reserved)
        {
            return Err(RendererActivationContractError::NonzeroReserved);
        }
        self.binding.validate()
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RendererActivationContractError {
    InvalidWireSize,
    InvalidStructSize,
    UnsupportedVersion,
    InvalidRuntimeGenerationId,
    InvalidProfileDigest,
    InvalidArchitecture,
    InvalidModuleLoad,
    InvalidActivationDisposition,
    InvalidActivationReason,
    InvalidIdentity,
    NonzeroReserved,
    NonzeroRequestOutput,
    InvalidCapabilityMask,
    OverlappingCapabilities,
    InconsistentEvidence,
}

impl fmt::Display for RendererActivationContractError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "renderer activation contract failed: {self:?}")
    }
}

impl std::error::Error for RendererActivationContractError {}

fn canonical_runtime_generation(value: &[u8]) -> bool {
    value.len() == RUNTIME_GENERATION_CANONICAL_CHARS && value.iter().copied().all(lower_hex)
}

fn canonical_runtime_generation_wire(value: &[u8; RUNTIME_GENERATION_TEXT_BYTES]) -> bool {
    canonical_runtime_generation(&value[..RUNTIME_GENERATION_CANONICAL_CHARS])
        && value[RUNTIME_GENERATION_CANONICAL_CHARS] == 0
}

fn canonical_profile_digest(value: &[u8]) -> bool {
    value.len() == PROFILE_DIGEST_CANONICAL_CHARS
        && value.starts_with(PROFILE_DIGEST_PREFIX.as_bytes())
        && value[PROFILE_DIGEST_PREFIX.len()..]
            .iter()
            .copied()
            .all(lower_hex)
}

fn canonical_profile_digest_wire(value: &[u8; PROFILE_DIGEST_TEXT_BYTES]) -> bool {
    canonical_profile_digest(&value[..PROFILE_DIGEST_CANONICAL_CHARS])
        && value[PROFILE_DIGEST_CANONICAL_CHARS] == 0
}

fn lower_hex(value: u8) -> bool {
    value.is_ascii_digit() || (b'a'..=b'f').contains(&value)
}

fn all_zero(value: &[u8]) -> bool {
    value.iter().all(|byte| *byte == 0)
}

fn put<const SIZE: usize>(wire: &mut [u8; SIZE], offset: usize, value: &[u8]) {
    wire[offset..offset + value.len()].copy_from_slice(value);
}

fn read_u16(bytes: &[u8], offset: usize) -> u16 {
    u16::from_le_bytes(
        bytes[offset..offset + 2]
            .try_into()
            .expect("fixed wire range"),
    )
}

fn read_u32(bytes: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes(
        bytes[offset..offset + 4]
            .try_into()
            .expect("fixed wire range"),
    )
}

fn read_u64(bytes: &[u8], offset: usize) -> u64 {
    u64::from_le_bytes(
        bytes[offset..offset + 8]
            .try_into()
            .expect("fixed wire range"),
    )
}

const _: () = {
    assert!(core::mem::size_of::<RendererRuntimeBinding>() == 137);
    assert!(core::mem::align_of::<RendererRuntimeBinding>() == 1);
    assert!(core::mem::size_of::<RendererActivationEvidenceV1>() == 312);
    assert!(core::mem::align_of::<RendererActivationEvidenceV1>() == 8);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, struct_size) == 0);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, schema_version) == 4);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, reason) == 6);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, architecture) == 8);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, module_load) == 9);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, disposition) == 10);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, reserved0) == 11);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, pid) == 12);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, session_id) == 16);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, reserved1) == 20);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, creation_time) == 24);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, binding) == 32);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, effective_profile_digest) == 169);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, reserved_alignment) == 241);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, lifecycle_revision) == 248);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, capability_active) == 256);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, capability_unavailable) == 264);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, capability_failed) == 272);
    assert!(core::mem::offset_of!(RendererActivationEvidenceV1, reserved) == 280);
};
