[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$sourceRoots = @(
    'control-center/src',
    'control-center/src-tauri/src',
    'preview-helper',
    'renderer',
    'service-injector',
    'service-runtime',
    'shared',
    'tools/service-probe'
)
$sourceExtensions = @(
    '.c', '.cc', '.cpp', '.h', '.hpp',
    '.js', '.mjs', '.rs', '.ts', '.tsx',
    '.css', '.scss', '.ps1', '.cmake'
)
$excludedPath = '(?i)[\\/](?:build|target|node_modules|fixtures|generated)[\\/]'
$excludedFile = '(?i)(?:renderer[\\/]json\.hpp|renderer_activation_contract\.h|renderer_activation\.rs|generated_settings\.(?:h|rs)|settings\.ts)$'
$taskMarker = '(?im)(?://|/\*|\*)[ \t]*(?:TODO|FIXME|HACK|XXX)\b'
$hashTaskMarker = '(?im)^\s*#[ \t]*(?:TODO|FIXME|HACK|XXX)\b'
$modelProvenance = '(?im)(?://|/\*|\*)[ \t]*(?:generated by[ \t]+)?(?:ChatGPT|Claude|LLM)(?:[ \t-]+(?:note|todo))?\b'

$failed = $false
$checked = 0
foreach ($sourceRoot in $sourceRoots) {
    if (-not (Test-Path -LiteralPath $sourceRoot -PathType Container)) {
        continue
    }
    $files = Get-ChildItem -LiteralPath $sourceRoot -Recurse -File | Where-Object {
        ($sourceExtensions -contains $_.Extension.ToLowerInvariant() -or $_.Name -eq 'CMakeLists.txt') -and
        $_.FullName -notmatch $excludedPath -and
        $_.FullName -notmatch $excludedFile
    }
    foreach ($file in $files) {
        $checked += 1
        $text = Get-Content -LiteralPath $file.FullName -Raw
        if ($null -eq $text) { $text = '' }
        $patterns = @($taskMarker, $modelProvenance)
        if ($file.Extension -in @('.ps1', '.cmake') -or $file.Name -eq 'CMakeLists.txt') {
            $patterns += $hashTaskMarker
        }
        foreach ($pattern in $patterns) {
            $matches = [regex]::Matches($text, $pattern)
            foreach ($match in $matches) {
                $line = 1 + ($text.Substring(0, $match.Index) -split "`n").Count - 1
                Write-Error "$($file.FullName):$line prohibited source-comment marker '$($match.Value.Trim())'" -ErrorAction Continue
                $failed = $true
            }
        }
    }
}

if ($failed) { exit 1 }
Write-Host "Source comment policy passed for $checked first-party files."
