// Generated by scripts/generate-unity-anticheat-catalog.mjs. Do not edit.
pub const ANTI_CHEAT_TOP_LEVEL_EXACT: &[&str] = &[
    "ace-base",
    "anticheatexpert",
    "battleye",
    "easyanticheat",
    "easyanticheat_eos",
    "gameguard",
    "nprotect",
    "wellbia",
    "x3.xem",
    "xigncode",
    "xigncode3",
];
pub const ANTI_CHEAT_TOP_LEVEL_PREFIXES: &[&str] = &[
    "ace-",
    "beclient",
    "beservice",
    "easyanticheat",
    "gameguard",
    "gamemon",
    "mhyprot",
    "xhunter",
];
