// Generated by scripts/generate-unity-anticheat-catalog.mjs. Do not edit.
#pragma once

namespace renderer { namespace unity {
static const wchar_t* const kAntiCheatTopLevelExact[] = {
	L"ace-base",
	L"anticheatexpert",
	L"battleye",
	L"easyanticheat",
	L"easyanticheat_eos",
	L"gameguard",
	L"nprotect",
	L"wellbia",
	L"x3.xem",
	L"xigncode",
	L"xigncode3",
};
static const wchar_t* const kAntiCheatTopLevelPrefixes[] = {
	L"ace-",
	L"beclient",
	L"beservice",
	L"easyanticheat",
	L"gameguard",
	L"gamemon",
	L"mhyprot",
	L"xhunter",
};
}} // namespace renderer::unity
