// Generated by scripts/generate-renderer-activation-contract.mjs. Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define MACTYPE_RENDERER_ACTIVATION_SCHEMA_VERSION 1U
#define MACTYPE_RENDERER_ACTIVATION_QUERY_EXPORT "MacTypeQueryActivationEvidenceV1"
#define MACTYPE_RENDERER_ACTIVATION_EVIDENCE_V1_SIZE 312U
#define MACTYPE_RENDERER_RUNTIME_GENERATION_CHARS 64U
#define MACTYPE_RENDERER_RUNTIME_GENERATION_BYTES 65U
#define MACTYPE_RENDERER_PROFILE_DIGEST_CHARS 71U
#define MACTYPE_RENDERER_PROFILE_DIGEST_BYTES 72U

typedef uint8_t MacTypeRendererArchitecture;
#define MACTYPE_RENDERER_ARCHITECTURE_X86 1U
#define MACTYPE_RENDERER_ARCHITECTURE_X64 2U

static inline const char* MacTypeRendererArchitectureCode(MacTypeRendererArchitecture value)
{
    switch (value)
    {
    case MACTYPE_RENDERER_ARCHITECTURE_X86:
        return "x86";
    case MACTYPE_RENDERER_ARCHITECTURE_X64:
        return "x64";
    default:
        return 0;
    }
}

typedef uint8_t MacTypeRendererModuleLoad;
#define MACTYPE_RENDERER_MODULE_LOAD_NOT_LOADED 1U
#define MACTYPE_RENDERER_MODULE_LOAD_LOADED_BY_REQUEST 2U
#define MACTYPE_RENDERER_MODULE_LOAD_ALREADY_LOADED 3U
#define MACTYPE_RENDERER_MODULE_LOAD_UNKNOWN 4U

static inline const char* MacTypeRendererModuleLoadCode(MacTypeRendererModuleLoad value)
{
    switch (value)
    {
    case MACTYPE_RENDERER_MODULE_LOAD_NOT_LOADED:
        return "not-loaded";
    case MACTYPE_RENDERER_MODULE_LOAD_LOADED_BY_REQUEST:
        return "loaded-by-request";
    case MACTYPE_RENDERER_MODULE_LOAD_ALREADY_LOADED:
        return "already-loaded";
    case MACTYPE_RENDERER_MODULE_LOAD_UNKNOWN:
        return "unknown";
    default:
        return 0;
    }
}

typedef uint8_t MacTypeRendererActivationDisposition;
#define MACTYPE_RENDERER_DISPOSITION_ACTIVE 1U
#define MACTYPE_RENDERER_DISPOSITION_QUIET_SKIP 2U
#define MACTYPE_RENDERER_DISPOSITION_FAILED 3U

static inline const char* MacTypeRendererActivationDispositionCode(MacTypeRendererActivationDisposition value)
{
    switch (value)
    {
    case MACTYPE_RENDERER_DISPOSITION_ACTIVE:
        return "active";
    case MACTYPE_RENDERER_DISPOSITION_QUIET_SKIP:
        return "quiet-skip";
    case MACTYPE_RENDERER_DISPOSITION_FAILED:
        return "failed";
    default:
        return 0;
    }
}

typedef uint16_t MacTypeRendererActivationReason;
#define MACTYPE_RENDERER_REASON_NONE 0U
#define MACTYPE_RENDERER_REASON_PROFILE_MISSING 1U
#define MACTYPE_RENDERER_REASON_PROFILE_INVALID 2U
#define MACTYPE_RENDERER_REASON_PROFILE_DIGEST_MISMATCH 3U
#define MACTYPE_RENDERER_REASON_PROCESS_EXCLUDED 4U
#define MACTYPE_RENDERER_REASON_PROCESS_UNLOAD_REQUESTED 5U
#define MACTYPE_RENDERER_REASON_RUNTIME_GENERATION_MISMATCH 6U
#define MACTYPE_RENDERER_REASON_INITIALIZATION_FAILED 7U
#define MACTYPE_RENDERER_REASON_HOOK_TRANSACTION_FAILED 8U
#define MACTYPE_RENDERER_REASON_LIFECYCLE_STOPPING 9U
#define MACTYPE_RENDERER_REASON_EVIDENCE_UNAVAILABLE 10U
#define MACTYPE_RENDERER_REASON_UNSUPPORTED_CONTRACT 11U
#define MACTYPE_RENDERER_REASON_MODULE_LOAD_FAILED 12U
#define MACTYPE_RENDERER_REASON_MODULE_UNLOAD_FAILED 13U

static inline const char* MacTypeRendererActivationReasonCode(MacTypeRendererActivationReason value)
{
    switch (value)
    {
    case MACTYPE_RENDERER_REASON_NONE:
        return "none";
    case MACTYPE_RENDERER_REASON_PROFILE_MISSING:
        return "profile-missing";
    case MACTYPE_RENDERER_REASON_PROFILE_INVALID:
        return "profile-invalid";
    case MACTYPE_RENDERER_REASON_PROFILE_DIGEST_MISMATCH:
        return "profile-digest-mismatch";
    case MACTYPE_RENDERER_REASON_PROCESS_EXCLUDED:
        return "process-excluded";
    case MACTYPE_RENDERER_REASON_PROCESS_UNLOAD_REQUESTED:
        return "process-unload-requested";
    case MACTYPE_RENDERER_REASON_RUNTIME_GENERATION_MISMATCH:
        return "runtime-generation-mismatch";
    case MACTYPE_RENDERER_REASON_INITIALIZATION_FAILED:
        return "initialization-failed";
    case MACTYPE_RENDERER_REASON_HOOK_TRANSACTION_FAILED:
        return "hook-transaction-failed";
    case MACTYPE_RENDERER_REASON_LIFECYCLE_STOPPING:
        return "lifecycle-stopping";
    case MACTYPE_RENDERER_REASON_EVIDENCE_UNAVAILABLE:
        return "evidence-unavailable";
    case MACTYPE_RENDERER_REASON_UNSUPPORTED_CONTRACT:
        return "unsupported-contract";
    case MACTYPE_RENDERER_REASON_MODULE_LOAD_FAILED:
        return "module-load-failed";
    case MACTYPE_RENDERER_REASON_MODULE_UNLOAD_FAILED:
        return "module-unload-failed";
    default:
        return 0;
    }
}

#define MACTYPE_RENDERER_CAPABILITY_GDI (UINT64_C(1) << 0U)
#define MACTYPE_RENDERER_CAPABILITY_CHILD_INJECTION (UINT64_C(1) << 1U)
#define MACTYPE_RENDERER_CAPABILITY_DIRECT_WRITE (UINT64_C(1) << 2U)
#define MACTYPE_RENDERER_CAPABILITY_DIRECT_WRITE_CORE (UINT64_C(1) << 3U)
#define MACTYPE_RENDERER_CAPABILITY_DIRECT2D (UINT64_C(1) << 4U)
#define MACTYPE_RENDERER_CAPABILITY_GDI_PLUS (UINT64_C(1) << 5U)
#define MACTYPE_RENDERER_CAPABILITY_FONT_SUBSTITUTION (UINT64_C(1) << 6U)
#define MACTYPE_RENDERER_CAPABILITY_UNITY_FONT (UINT64_C(1) << 7U)
#define MACTYPE_RENDERER_CAPABILITY_KNOWN_MASK (MACTYPE_RENDERER_CAPABILITY_GDI | MACTYPE_RENDERER_CAPABILITY_CHILD_INJECTION | MACTYPE_RENDERER_CAPABILITY_DIRECT_WRITE | MACTYPE_RENDERER_CAPABILITY_DIRECT_WRITE_CORE | MACTYPE_RENDERER_CAPABILITY_DIRECT2D | MACTYPE_RENDERER_CAPABILITY_GDI_PLUS | MACTYPE_RENDERER_CAPABILITY_FONT_SUBSTITUTION | MACTYPE_RENDERER_CAPABILITY_UNITY_FONT)

static inline const char* MacTypeRendererCapabilityCode(uint64_t capability)
{
    switch (capability)
    {
    case MACTYPE_RENDERER_CAPABILITY_GDI:
        return "gdi";
    case MACTYPE_RENDERER_CAPABILITY_CHILD_INJECTION:
        return "child-injection";
    case MACTYPE_RENDERER_CAPABILITY_DIRECT_WRITE:
        return "direct-write";
    case MACTYPE_RENDERER_CAPABILITY_DIRECT_WRITE_CORE:
        return "direct-write-core";
    case MACTYPE_RENDERER_CAPABILITY_DIRECT2D:
        return "direct2d";
    case MACTYPE_RENDERER_CAPABILITY_GDI_PLUS:
        return "gdi-plus";
    case MACTYPE_RENDERER_CAPABILITY_FONT_SUBSTITUTION:
        return "font-substitution";
    case MACTYPE_RENDERER_CAPABILITY_UNITY_FONT:
        return "unity-font";
    default:
        return 0;
    }
}

typedef struct MacTypeRendererRuntimeBindingV1
{
    char runtime_generation_id[65];
    char profile_digest[72];
} MacTypeRendererRuntimeBindingV1;

#if defined(_MSC_VER)
#define MACTYPE_RENDERER_ALIGN_8 __declspec(align(8))
#elif defined(__GNUC__)
#define MACTYPE_RENDERER_ALIGN_8 __attribute__((aligned(8)))
#else
#define MACTYPE_RENDERER_ALIGN_8
#endif

typedef struct MACTYPE_RENDERER_ALIGN_8 MacTypeRendererActivationEvidenceV1
{
    uint32_t struct_size;
    uint16_t schema_version;
    uint16_t reason;
    uint8_t architecture;
    uint8_t module_load;
    uint8_t disposition;
    uint8_t reserved0;
    uint32_t pid;
    uint32_t session_id;
    uint32_t reserved1;
    uint64_t creation_time;
    MacTypeRendererRuntimeBindingV1 binding;
    char effective_profile_digest[72];
    uint8_t reserved_alignment[7];
    uint64_t lifecycle_revision;
    uint64_t capability_active;
    uint64_t capability_unavailable;
    uint64_t capability_failed;
    uint8_t reserved[32];
} MacTypeRendererActivationEvidenceV1;

#if defined(_WIN32)
#define MACTYPE_RENDERER_CALL __stdcall
#else
#define MACTYPE_RENDERER_CALL
#endif

typedef uint32_t (MACTYPE_RENDERER_CALL *MacTypeRendererActivationQueryV1)(
    MacTypeRendererActivationEvidenceV1* in_out_evidence);

#if defined(__cplusplus)
#define MACTYPE_RENDERER_STATIC_ASSERT(condition, message) static_assert(condition, message)
#define MACTYPE_RENDERER_ALIGNOF(type) alignof(type)
#elif defined(_MSC_VER)
#define MACTYPE_RENDERER_JOIN_INNER(left, right) left##right
#define MACTYPE_RENDERER_JOIN(left, right) MACTYPE_RENDERER_JOIN_INNER(left, right)
#define MACTYPE_RENDERER_STATIC_ASSERT(condition, message) \
    typedef char MACTYPE_RENDERER_JOIN(mactype_renderer_static_assert_, __LINE__)[(condition) ? 1 : -1]
#define MACTYPE_RENDERER_ALIGNOF(type) __alignof(type)
#else
#define MACTYPE_RENDERER_STATIC_ASSERT(condition, message) _Static_assert(condition, message)
#define MACTYPE_RENDERER_ALIGNOF(type) _Alignof(type)
#endif

MACTYPE_RENDERER_STATIC_ASSERT(sizeof(MacTypeRendererRuntimeBindingV1) == 137U,
                               "MacTypeRendererRuntimeBindingV1 size changed");
MACTYPE_RENDERER_STATIC_ASSERT(MACTYPE_RENDERER_ALIGNOF(MacTypeRendererRuntimeBindingV1) == 1U,
                               "MacTypeRendererRuntimeBindingV1 alignment changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererRuntimeBindingV1, runtime_generation_id) == 0U,
                               "MacTypeRendererRuntimeBindingV1.runtime_generation_id offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererRuntimeBindingV1, profile_digest) == 65U,
                               "MacTypeRendererRuntimeBindingV1.profile_digest offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(sizeof(MacTypeRendererActivationEvidenceV1) == 312U,
                               "MacTypeRendererActivationEvidenceV1 size changed");
MACTYPE_RENDERER_STATIC_ASSERT(MACTYPE_RENDERER_ALIGNOF(MacTypeRendererActivationEvidenceV1) == 8U,
                               "MacTypeRendererActivationEvidenceV1 alignment changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, struct_size) == 0U,
                               "MacTypeRendererActivationEvidenceV1.struct_size offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, schema_version) == 4U,
                               "MacTypeRendererActivationEvidenceV1.schema_version offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, reason) == 6U,
                               "MacTypeRendererActivationEvidenceV1.reason offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, architecture) == 8U,
                               "MacTypeRendererActivationEvidenceV1.architecture offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, module_load) == 9U,
                               "MacTypeRendererActivationEvidenceV1.module_load offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, disposition) == 10U,
                               "MacTypeRendererActivationEvidenceV1.disposition offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, reserved0) == 11U,
                               "MacTypeRendererActivationEvidenceV1.reserved0 offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, pid) == 12U,
                               "MacTypeRendererActivationEvidenceV1.pid offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, session_id) == 16U,
                               "MacTypeRendererActivationEvidenceV1.session_id offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, reserved1) == 20U,
                               "MacTypeRendererActivationEvidenceV1.reserved1 offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, creation_time) == 24U,
                               "MacTypeRendererActivationEvidenceV1.creation_time offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, binding) == 32U,
                               "MacTypeRendererActivationEvidenceV1.binding offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, effective_profile_digest) == 169U,
                               "MacTypeRendererActivationEvidenceV1.effective_profile_digest offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, reserved_alignment) == 241U,
                               "MacTypeRendererActivationEvidenceV1.reserved_alignment offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, lifecycle_revision) == 248U,
                               "MacTypeRendererActivationEvidenceV1.lifecycle_revision offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, capability_active) == 256U,
                               "MacTypeRendererActivationEvidenceV1.capability_active offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, capability_unavailable) == 264U,
                               "MacTypeRendererActivationEvidenceV1.capability_unavailable offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, capability_failed) == 272U,
                               "MacTypeRendererActivationEvidenceV1.capability_failed offset changed");
MACTYPE_RENDERER_STATIC_ASSERT(offsetof(MacTypeRendererActivationEvidenceV1, reserved) == 280U,
                               "MacTypeRendererActivationEvidenceV1.reserved offset changed");

static inline int MacTypeRendererIsLowerHex(char value)
{
    return (value >= '0' && value <= '9') || (value >= 'a' && value <= 'f');
}

static inline int MacTypeRendererRuntimeGenerationIsCanonical(
    const char value[MACTYPE_RENDERER_RUNTIME_GENERATION_BYTES])
{
    size_t index;
    for (index = 0; index < MACTYPE_RENDERER_RUNTIME_GENERATION_CHARS; ++index)
    {
        if (!MacTypeRendererIsLowerHex(value[index]))
            return 0;
    }
    return value[MACTYPE_RENDERER_RUNTIME_GENERATION_CHARS] == '\0';
}

static inline int MacTypeRendererProfileDigestIsCanonical(
    const char value[MACTYPE_RENDERER_PROFILE_DIGEST_BYTES])
{
    static const char prefix[] = "sha256:";
    size_t index;
    for (index = 0; index < sizeof(prefix) - 1U; ++index)
    {
        if (value[index] != prefix[index])
            return 0;
    }
    for (; index < MACTYPE_RENDERER_PROFILE_DIGEST_CHARS; ++index)
    {
        if (!MacTypeRendererIsLowerHex(value[index]))
            return 0;
    }
    return value[MACTYPE_RENDERER_PROFILE_DIGEST_CHARS] == '\0';
}

static inline int MacTypeRendererBytesAreZero(const uint8_t* value, size_t size)
{
    size_t index;
    for (index = 0; index < size; ++index)
    {
        if (value[index] != 0U)
            return 0;
    }
    return 1;
}

static inline int MacTypeRendererBindingIsCanonical(
    const MacTypeRendererRuntimeBindingV1* binding)
{
    return binding != 0 &&
           MacTypeRendererRuntimeGenerationIsCanonical(binding->runtime_generation_id) &&
           MacTypeRendererProfileDigestIsCanonical(binding->profile_digest);
}

static inline int MacTypeRendererActivationCommonIsValid(
    const MacTypeRendererActivationEvidenceV1* evidence)
{
    return evidence != 0 &&
           evidence->struct_size == MACTYPE_RENDERER_ACTIVATION_EVIDENCE_V1_SIZE &&
           evidence->schema_version == MACTYPE_RENDERER_ACTIVATION_SCHEMA_VERSION &&
           MacTypeRendererArchitectureCode(evidence->architecture) != 0 &&
           evidence->pid != 0U && evidence->creation_time != 0U &&
           evidence->session_id != 0U && evidence->reserved0 == 0U &&
           evidence->reserved1 == 0U &&
           MacTypeRendererBytesAreZero(evidence->reserved_alignment,
                                       sizeof(evidence->reserved_alignment)) &&
           MacTypeRendererBytesAreZero(evidence->reserved, sizeof(evidence->reserved)) &&
           MacTypeRendererBindingIsCanonical(&evidence->binding);
}

static inline int MacTypeValidateRendererActivationRequestV1(
    const MacTypeRendererActivationEvidenceV1* request)
{
    return MacTypeRendererActivationCommonIsValid(request) &&
           request->reason == MACTYPE_RENDERER_REASON_NONE &&
           (request->module_load == MACTYPE_RENDERER_MODULE_LOAD_LOADED_BY_REQUEST ||
            request->module_load == MACTYPE_RENDERER_MODULE_LOAD_ALREADY_LOADED) &&
           request->disposition == 0U && request->lifecycle_revision == 0U &&
           request->capability_active == 0U && request->capability_unavailable == 0U &&
           request->capability_failed == 0U &&
           MacTypeRendererBytesAreZero((const uint8_t*)request->effective_profile_digest,
                                       sizeof(request->effective_profile_digest));
}

static inline int MacTypeValidateRendererActivationEvidenceV1(
    const MacTypeRendererActivationEvidenceV1* evidence)
{
    uint64_t all_capabilities;
    int effective_is_empty;
    int effective_is_canonical;
    if (!MacTypeRendererActivationCommonIsValid(evidence) ||
        MacTypeRendererModuleLoadCode(evidence->module_load) == 0 ||
        MacTypeRendererActivationDispositionCode(evidence->disposition) == 0 ||
        MacTypeRendererActivationReasonCode(evidence->reason) == 0)
        return 0;
    all_capabilities = evidence->capability_active | evidence->capability_unavailable |
                       evidence->capability_failed;
    if ((all_capabilities & ~MACTYPE_RENDERER_CAPABILITY_KNOWN_MASK) != 0U ||
        (evidence->capability_active & evidence->capability_unavailable) != 0U ||
        (evidence->capability_active & evidence->capability_failed) != 0U ||
        (evidence->capability_unavailable & evidence->capability_failed) != 0U)
        return 0;
    effective_is_empty = MacTypeRendererBytesAreZero(
        (const uint8_t*)evidence->effective_profile_digest,
        sizeof(evidence->effective_profile_digest));
    effective_is_canonical = !effective_is_empty &&
        MacTypeRendererProfileDigestIsCanonical(evidence->effective_profile_digest);
    if (!effective_is_empty && !effective_is_canonical)
        return 0;
    if (evidence->disposition == MACTYPE_RENDERER_DISPOSITION_ACTIVE)
    {
        return (evidence->module_load == MACTYPE_RENDERER_MODULE_LOAD_LOADED_BY_REQUEST ||
                evidence->module_load == MACTYPE_RENDERER_MODULE_LOAD_ALREADY_LOADED) &&
               evidence->reason == MACTYPE_RENDERER_REASON_NONE &&
               evidence->lifecycle_revision != 0U &&
               effective_is_canonical &&
               memcmp(evidence->effective_profile_digest, evidence->binding.profile_digest,
                      MACTYPE_RENDERER_PROFILE_DIGEST_BYTES) == 0;
    }
    if (evidence->disposition == MACTYPE_RENDERER_DISPOSITION_QUIET_SKIP)
    {
        return (evidence->module_load == MACTYPE_RENDERER_MODULE_LOAD_LOADED_BY_REQUEST ||
                evidence->module_load == MACTYPE_RENDERER_MODULE_LOAD_ALREADY_LOADED) &&
               evidence->reason != MACTYPE_RENDERER_REASON_NONE &&
               evidence->lifecycle_revision != 0U && evidence->capability_active == 0U &&
               evidence->capability_failed == 0U && effective_is_canonical &&
               memcmp(evidence->effective_profile_digest, evidence->binding.profile_digest,
                      MACTYPE_RENDERER_PROFILE_DIGEST_BYTES) == 0;
    }
    return evidence->disposition == MACTYPE_RENDERER_DISPOSITION_FAILED &&
           evidence->reason != MACTYPE_RENDERER_REASON_NONE;
}

#undef MACTYPE_RENDERER_ALIGN_8
#undef MACTYPE_RENDERER_ALIGNOF
#undef MACTYPE_RENDERER_CALL
#undef MACTYPE_RENDERER_JOIN
#undef MACTYPE_RENDERER_JOIN_INNER
#undef MACTYPE_RENDERER_STATIC_ASSERT
