// Generated by scripts/generate-settings.mjs. Do not edit.
#pragma once

#include <array>

namespace mactype {
struct SettingDefinition { const char* id; int ordinal; bool is_float; };
inline constexpr std::array<SettingDefinition, 9> kSettings{{
    {"hinting_mode", 0, false},
    {"anti_alias_mode", 1, false},
    {"normal_weight", 2, false},
    {"bold_weight", 3, false},
    {"italic_slant", 4, false},
    {"enable_kerning", 5, false},
    {"gamma_value", 13, true},
    {"contrast", 14, true},
    {"render_weight", 15, true},
}};
}  // namespace mactype
