// Generated by scripts/generate-native-preview-contract.mjs. Do not edit.
#pragma once

#include <Windows.h>

#include <array>
#include <string>

namespace mactype {

enum class NativeLabelId {
  title,
  font_face,
  font_size,
  bold,
  italic,
  mode_sample,
  mode_ladder,
  mode_compare,
  mode_listing,
  invert,
  loupe,
  zoom,
  topmost,
  edit_text,
  save_png,
  copy,
  compare_mac_type,
  compare_windows,
  compare_unavailable,
  engine_mac_type,
  core_version,
  png_filter,
  saved,
  copied,
};

struct GeneratedNativeLabelBinding {
  NativeLabelId id;
  const char* key;
  std::wstring PreviewRuntime::NativePreviewLabels::*member;
};

struct GeneratedNativePalette {
  COLORREF canvas;
  COLORREF surface;
  COLORREF hover;
  COLORREF border;
  COLORREF text;
  COLORREF muted;
  COLORREF accent;
  COLORREF on_accent;
};

struct GeneratedNativeChrome {
  int radius;
  int control_height;
  int toolbar_height;
  int status_height;
  int canvas_radius;
  int canvas_inset;
  bool mono_status;
};

inline constexpr std::array<GeneratedNativeLabelBinding, 24> kNativeLabelBindings{{
    {NativeLabelId::title, "title", &PreviewRuntime::NativePreviewLabels::title},
    {NativeLabelId::font_face, "fontFace", &PreviewRuntime::NativePreviewLabels::font_face},
    {NativeLabelId::font_size, "fontSize", &PreviewRuntime::NativePreviewLabels::font_size},
    {NativeLabelId::bold, "bold", &PreviewRuntime::NativePreviewLabels::bold},
    {NativeLabelId::italic, "italic", &PreviewRuntime::NativePreviewLabels::italic},
    {NativeLabelId::mode_sample, "modeSample", &PreviewRuntime::NativePreviewLabels::mode_sample},
    {NativeLabelId::mode_ladder, "modeLadder", &PreviewRuntime::NativePreviewLabels::mode_ladder},
    {NativeLabelId::mode_compare, "modeCompare", &PreviewRuntime::NativePreviewLabels::mode_compare},
    {NativeLabelId::mode_listing, "modeListing", &PreviewRuntime::NativePreviewLabels::mode_listing},
    {NativeLabelId::invert, "invert", &PreviewRuntime::NativePreviewLabels::invert},
    {NativeLabelId::loupe, "loupe", &PreviewRuntime::NativePreviewLabels::loupe},
    {NativeLabelId::zoom, "zoom", &PreviewRuntime::NativePreviewLabels::zoom},
    {NativeLabelId::topmost, "topmost", &PreviewRuntime::NativePreviewLabels::topmost},
    {NativeLabelId::edit_text, "editText", &PreviewRuntime::NativePreviewLabels::edit_text},
    {NativeLabelId::save_png, "savePng", &PreviewRuntime::NativePreviewLabels::save_png},
    {NativeLabelId::copy, "copy", &PreviewRuntime::NativePreviewLabels::copy},
    {NativeLabelId::compare_mac_type, "compareMacType", &PreviewRuntime::NativePreviewLabels::compare_mactype},
    {NativeLabelId::compare_windows, "compareWindows", &PreviewRuntime::NativePreviewLabels::compare_windows},
    {NativeLabelId::compare_unavailable, "compareUnavailable", &PreviewRuntime::NativePreviewLabels::compare_unavailable},
    {NativeLabelId::engine_mac_type, "engineMacType", &PreviewRuntime::NativePreviewLabels::engine_mactype},
    {NativeLabelId::core_version, "coreVersion", &PreviewRuntime::NativePreviewLabels::core_version},
    {NativeLabelId::png_filter, "pngFilter", &PreviewRuntime::NativePreviewLabels::png_filter},
    {NativeLabelId::saved, "saved", &PreviewRuntime::NativePreviewLabels::saved},
    {NativeLabelId::copied, "copied", &PreviewRuntime::NativePreviewLabels::copied},
}};
inline constexpr std::array<const wchar_t*, 24> kNativeLabelDefaults{{
    L"MacType Preview",
    L"Font",
    L"Size",
    L"B",
    L"I",
    L"Sample",
    L"Ladder",
    L"Compare",
    L"Listing",
    L"Invert",
    L"Loupe",
    L"Zoom",
    L"Top",
    L"Edit",
    L"Save",
    L"Copy",
    L"MacType",
    L"Windows",
    L"Comparison unavailable",
    L"MacType",
    L"Core {version}",
    L"PNG files (*.png)|*.png",
    L"Saved",
    L"Copied",
}};
inline constexpr GeneratedNativePalette kNativeLightPalette{RGB(0xF3, 0xF5, 0xF7), RGB(0xFF, 0xFF, 0xFF), RGB(0xE9, 0xED, 0xF1), RGB(0xC9, 0xD1, 0xD8), RGB(0x17, 0x21, 0x2B), RGB(0x5A, 0x67, 0x73), RGB(0x00, 0x67, 0xC0), RGB(0xFF, 0xFF, 0xFF)};
inline constexpr GeneratedNativePalette kNativeDarkPalette{RGB(0x11, 0x16, 0x1B), RGB(0x19, 0x20, 0x27), RGB(0x22, 0x2B, 0x33), RGB(0x34, 0x41, 0x4C), RGB(0xE8, 0xED, 0xF2), RGB(0x9A, 0xA8, 0xB5), RGB(0x4C, 0xA6, 0xE8), RGB(0x07, 0x13, 0x1C)};
inline constexpr GeneratedNativeChrome kNativeChromeDefault{
    4, 32, 44, 28,
    4, 18, false};
inline constexpr std::array<float, 10> kNativeLadderSizes{8.0F, 9.0F, 10.0F, 11.0F, 12.0F, 14.0F, 16.0F, 18.0F, 20.0F, 24.0F};

}
